### ISSUE TITLE
cbindgen should emit its version number into the generated file

### ISSUE THREAD

**Issue by staktrace** [rlhunt/cbindgen#1]
If you use `cargo install cbindgen` to install cbindgen, you will get the version currently published to crates.io. If we subsequently push new versions to crates.io, you will need to run `cargo install --force cbindgen` to get the latest version. People might forget to do this, and we will eventually run into the situation where people run an older version of cbindgen and inadvertently roll back changes to the generated file. For example say a new version of cbindgen ends up reordering a couple of things in the generated file, and we check in that new version. Later somebody using an older version of cbindgen regenerates the file, those things will back to their old ordering. This might still compile and run but it's a spurious change.

I think a stopgap solution (until we have cbindgen plugged into the build workflow and automatically updating) is to emit the cbindgen version number into the generated file. That way if somebody uses an older version of cbindgen the version number change will show up in the diff and we're more likely to catch it.

**Comment by rlhunt** [comment]
I added Config::include_version to handle this and enabled it in the webrender config, so this should be fixed.
