### ISSUE TITLE
Add option to prefix enum variants

### ISSUE THREAD

**Issue by mitsuhiko** [rlhunt/cbindgen#20]
Currently when you make an enum they end up with the field names in the header. I think it would not be unreasonable to add an option to prefix them with the type.

Eg:

```rust
#[repr(u32)]
struct FooBar {
    A = 1,
    B,
    C
}
```

Would end up something like this:

```c
enum FooBar {
    FOO_BAR_A = 1,
    FOO_BAR_B = 2,
    FOO_BAR_C = 3
}
typedef uint32_t FooBar;
```

**Comment by rlhunt** [comment]
This was merged.
