### ISSUE TITLE
Missing include for generated code

### ISSUE THREAD

**Issue by weiznich** [rlhunt/cbindgen#22]
cbindgen translates the following rust code:
```rust 
#[repr(C)]
struct Foo {
    dummy: usize
}
```
into the following c++ code:
```c++
struct Foo {
    size_t dummy;
};
```

gcc will reject the generated code with the following error message:
```
error: ‘size_t’ does not name a type
     size_t dummy;
     ^~~~~~
```

This could be fixed by including for example `#include<cstdlib>`

**Comment by rlhunt** [comment]
Whoops. `<cstdlib>` or `<stdlib.h>` should be included in all headers now depending on whether they are C++ or C. Let me know if there are still problems. Thanks!
