### ISSUE TITLE
Publish version 0.1.12 to crates.io

### ISSUE THREAD

**Issue by weiznich** [rlhunt/cbindgen#23]
The current version on crates.io is `0.1.10`, whereas the repository contains already version `0.1.12`.

**Comment by rlhunt** [comment]
This is kind of intentional, because Gecko is currently using an older version of cbindgen.

I've been working to do a major update to the WebRender bindings simultaneously with a new crates.io release, but that looks like it'll be delayed. I'll do a crates.io release separately.

**Comment by rlhunt** [comment]
I've just published 0.1.13.
