### ISSUE TITLE
Build script fails if crate is built as a dependency

### ISSUE THREAD

**Issue by WrinklyNinja** [rlhunt/cbindgen#25]
I've got a crate using cbindgen in its build script, and everything works (aside from builds using cargo-travis, but I'll file a different bug for that) when I build the crate directly, but if I have it as a dependency and build the dependent crate, I get an odd error. Here's the relevant output of `RUST_BACKTRACE=1 cargo build -v` from the dependent crate:

```
   Compiling libespm v0.1.0 (https://github.com/WrinklyNinja/libespm?branch=rust-rewrite#4afc26da)
     Running `rustc --crate-name build_script_build /home/oliver/.cargo/git/checkouts/libespm-add271feea385607/4afc26d/build.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' -C metadata=ffa693acaa10afaa -C extra-filename=-ffa693acaa10afaa --out-dir /home/oliver/Documents/Code/libloadorder/target/debug/build/libespm-ffa693acaa10afaa -L dependency=/home/oliver/Documents/Code/libloadorder/target/debug/deps --extern cbindgen=/home/oliver/Documents/Code/libloadorder/target/debug/deps/libcbindgen-9c2f32f2141e6cd7.rlib --cap-lints allow`
     Running `/home/oliver/Documents/Code/libloadorder/target/debug/build/libespm-ffa693acaa10afaa/build-script-build`
error: failed to run custom build command for `libespm v0.1.0 (https://github.com/WrinklyNinja/libespm?branch=rust-rewrite#4afc26da)`
process didn't exit successfully: `/home/oliver/Documents/Code/libloadorder/target/debug/build/libespm-ffa693acaa10afaa/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "couldn\'t load \"/home/oliver/.cargo/git/checkouts/libespm-add271feea385607/4afc26d/Cargo.lock\": Io(Error { repr: Os { code: 2, message: \"No such file or directory\" } })"', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:737
  11: build_script_build::main
             at ./build.rs:18
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  13: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  14: main
  15: __libc_start_main
  16: _start
```

Sure enough, Cargo.lock doesn't get generated at the given path, though one is generated if I `cd` there and run `cargo build` there (and after that building the dependent crate works).

The dependency's `build.rs` is:

```rust
fn main() {
    // Don't run cbindgen if it's not cargo being run
    // (i.e. not for cargo coveralls)
    if !env::var("CARGO").unwrap().ends_with("cargo") {
        return;
    }

    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    fs::create_dir_all("include").expect("could not create include directory");

    cbindgen::generate(&crate_dir).unwrap().write_to_file(
        "include/libespm.h",
    );

    let mut config = cbindgen::Config::from_root_or_default(PathBuf::from(&crate_dir).as_path());
    config.language = cbindgen::Language::Cxx;
    cbindgen::generate_with_config(&crate_dir, &config)
        .unwrap()
        .write_to_file("include/libespm.hpp");
}
```

Builds also work if I comment out the cbindgen calls.

**Comment by rlhunt** [comment]
Thanks for the detailed issue!

Hmm, so generating bindings for a crate requires that it has a Cargo.lock generated. This is a limitation of the `cargo metadata` command, as it doesn't give us precise version information to determine the correct dependencies.

We've run into this problem in Gecko with `webrender` as it is used as a dependent crate and so it doesn't have a Cargo.lock. The CLI supports specifying the path to the crate being built and also the name of the binding crate, for this reason. So you can do,
```sh
cbindgen path/to/crate/being/built --crate name_of_crate_to_generate_bindings_for
```
And it will use the Cargo.lock of the crate being built and generate bindings for the dependent crate.

Unfortunately, there doesn't seem to be any standard way of determining the path to the 'root' crate inside a build script. Or to even determine if the build script is being used for a dependent crate.

But, if you don't need types from the dependencies of this binding crate, we really shouldn't need a Cargo.lock. That would probably work for this case, I'll look into adding a fix for this.

If in the future someone does need the dependency parsing, the options I see are:
1. Try and upstream an env var that can be used to determine the path of the root crate being built, or at the least the Cargo.lock
1. Try and upstream a way to not need the Cargo.lock

**Comment by WrinklyNinja** [comment]
Well, the only types I expose are my own and libc's (which is a special case for `moz-cheddar`, I expect it's the same for cbindgen?) so I don't need dependency parsing. I have configured `parse_deps = false` for that reason, gating the Cargo.lock requirement on that would be great.

In the meantime, I suppose I could remove binding generation from my dependency, and generate them for that dependency in my dependent's build script? That would probably work for me as my dependency doesn't actually test the headers generated, so doesn't need them to exist for its own build process, but it's not a general solution.

**Comment by rlhunt** [comment]
> In the meantime, I suppose I could remove binding generation from my dependency, and generate them for that dependency in my dependent's build script? That would probably work for me as my dependency doesn't actually test the headers generated, so doesn't need them to exist for its own build process, but it's not a general solution.

That would work, but unfortunately the `cbindgen::{generate, generate_with_config}` don't support specifying the binding crate name like the CLI does.

It's an easy change so I'll try and fix that too.

**Comment by rlhunt** [comment]
I've added 1bd5f1e776971ec855bf6c02083f20c461c8301b which makes it so that Cargo.lock is only parsed when `config.parse.parse_deps = true` (but only when using cbindgen::{generate, generate_with_config}, because when using the CLI the config can depend on Cargo.lock...)

Let me know if this fixes you problem, and I'll post a new release.

**Comment by WrinklyNinja** [comment]
Yes, that works for me. Thank you for fixing this so quickly, and for the library! :+1:

**Comment by rlhunt** [comment]
Okay, thanks!

**Comment by ShayRubach** [comment]
Btw - I failed to generate the header file by following the quick guide in the main page, using:
`cbindgen --config cbindgen.toml --crate my_rust_library.a --output my_header.h`
Specifying the path/to/lib.rs as suggested here above fixed the issue and I was able to get my header file, using:
`cbindgen --config cbindgen.toml path/to/crate/being/built --crate my_rust_library.a --output my_header.h`

Worth mentioning it in the main page I assume.
