### ISSUE TITLE
Don't use C enum when generating C language bindings

### ISSUE THREAD

**Issue by rlhunt** [rlhunt/cbindgen#8]
C enums don't have an explicit size and so aren't FFI safe.

`cbindgen` currently incorrectly generates them when in C language mode. In C++ mode `cbindgen` uses `enum class` which can be typed correctly.

**Comment by canndrew** [comment]
@eqrion I asked about this on the rust-users forum and it seems that enums are more safe than you realise: https://users.rust-lang.org/t/what-exactly-does-repr-c-mean-on-an-enum/12833

It's probably worth reconsidering whether this was a bug.

**Comment by eqrion** [comment]
Yes, that sounds right to me.

I don't remember the reason this was feared originally but I think it should be okay to just emit normal C enum's in C language mode.
